# Generated by Django 5.0.2 on 2025-04-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sessions', models.IntegerField()),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('equipment_utilization_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_hours_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_bookings', models.IntegerField()),
                ('maintenance_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('equipment', 'date')},
            },
        ),
    ]
