# Generated by Django 5.0.2 on 2025-04-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('CHEMICALS', 'Chemicals'), ('GLASSWARE', 'Glassware'), ('EQUIPMENT', 'Equipment'), ('CONSUMABLES', 'Consumables'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
