# Generated by Django 5.0.2 on 2025-04-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
        ('accounts', '0002_create_default_site'),
    ]

    operations = [
    ]
