# Generated by Django 5.0.2 on 2025-04-26 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
        migrations.RemoveField(
            model_name='report',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_date',
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='report',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('equipment_usage', 'Equipment Usage'), ('maintenance', 'Maintenance Report'), ('inventory', 'Inventory Status'), ('booking_analytics', 'Booking Analytics'), ('user_activity', 'User Activity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
